import { ContextProvider } from "@/context/context";
import Link from "next/link";
import "./globals.css";
import NavBar from "./Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ContextProvider>
        <body className="min-h-screen">
          <NavBar />
          <main>{children}</main>
        </body>
      </ContextProvider>
    </html>
  );
}
