import { ContextProvider } from "@/context/context";
import "./globals.css";
import Sidebar from "./components/layout/Sidebar";
import NavBar from "./components/layout/Navbar";

export const metadata = {
  title: "Portfolio | Johann Ranudd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <ContextProvider>
        <body className="relative min-h-screen">
          <NavBar />
          <div className="max-w-screen-2xl mx-auto">
            <Sidebar />
            <main>{children}</main>
          </div>
        </body>
      </ContextProvider>
    </html>
  );
}
